=== uoscompsci/PRISONER/xsd/experimental_design.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://prisoner.cs.st-andrews.ac.uk/prisoner/experimental_design"
xmlns:tns="http://prisoner.cs.st-andrews.ac.uk/prisoner/experimental_design"
elementFormDefault="unqualified">

<xs:complexType name="column">
	<xs:annotation>
		<xs:documentation>
			Represents a column in a table of persistent
			experimental data.
		</xs:documentation>
	</xs:annotation>
	<xs:attribute name="name" use="required" type="xs:string" />
	<xs:attribute name="type" type="xs:string" />
	<xs:attribute name="mapTo" type="xs:string" />
</xs:complexType>

<xs:complexType name="table">
	<xs:annotation>
		<xs:documentation>
			Represents a table of persistent experimental data.
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="column" type="tns:column" minOccurs="1"
		maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="name" use="required" type="xs:string" />
	<xs:attribute name="type" type="xs:string" />
	<xs:attribute name="mapTo" type="xs:string" />
</xs:complexType>

<xs:complexType name="tables">
	<xs:annotation>
		<xs:documentation>
			A set of all tables used in the experiment to persist
			data.
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="table" type="tns:table" minOccurs="1" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="experiment">
	<xs:annotation>
		<xs:documentation>
			Root of the experiment. Contains additional metadata
			about the experiment itself.
		</xs:documentation>
	</xs:annotation>
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="tables" type="tns:tables" />
	</xs:sequence>
	<xs:attribute name="name" use="required" type="xs:string" />
</xs:complexType>



<xs:element name="experimental-design">
	<xs:annotation>
		<xs:documentation>
			Root element of any experimental design. The tables for
			this experiment are contained within this element.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="experiment" type="tns:experiment" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== uoscompsci/PRISONER/web/Facebook/xml/fb_exp_design_test.xml
<p:experimental-design xmlns:p="http://pvnets.cs.st-andrews.ac.uk/prisoner/experimental_design" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pvnets.cs.st-andrews.ac.uk/prisoner/experimental_design.xsd">

	<experiment name="FacebookDummy">
		<tables>
			<table name="participant" type="participant">
				<column name="name" type="string" />
			</table>
			<table name="response" type="response">
				<column name="group_id" type="string" />
				<column name="info_type" type="string" />
				<column name="privacy" type="string" />
				<column name="response" type="string" />
			</table>
		</tables>
	</experiment>
</p:experimental-design>

=== uoscompsci/PRISONER/web/Facebook/xml/facebook_study_exp_design.xml
<p:experimental-design xmlns:p="http://prisoner.cs.st-andrews.ac.uk/prisoner/experimental_design" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://prisoner.cs.st-andrews.ac.uk/prisoner/experimental_design.xsd">

	<experiment name="Facebook_Study">
		<tables>
			<table name="participant" type="participant">
				<column name="name" type="string" />
			</table>
			<table name="response" type="response">
				<column name="participant_id" type="string" />
				<column name="group_id" type="string" />
				<column name="info_type" type="string" />
				<column name="privacy" type="string" />
				<column name="response" type="string" />
			</table>
		</tables>
	</experiment>
</p:experimental-design>
